name: emuscd CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '*' ]
  create:
      tags: ['v*']

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest,  cc: g++-10,  dep: 'build-essential cmake g++-10' }
          - { os: macos-latest,   cc: clang++, dep: '' }
          - { os: windows-latest, cc: g++,     dep: '' }
    runs-on: ${{matrix.os}}
    steps:
    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ${{matrix.dep}}

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
